### PR TITLE
Use configuration to set queue/gpm host:port and allowed channels

### PR DESCRIPTION
**Pull request by braedon**

### CODE REVIEW

**Comment by echojc** [comment]
What's the reason for importing the standard `JsonFormat`s globally instead of isolating them in the companion objects?

**Comment by braedon** [comment]
Having multiple `JsonProtocols` floating around (by extending `DefaultJsonProtocol` lots of places) has caused some issues before. You can end up importing the same `JsonFormat`s multiple times from different `JsonProtocols`s, which can cause weird resolution issues.

**Comment by echojc** [comment]
Right, that's why I tuck them away into each case class's companion object so that you don't need to explicitly import them. I think having them in the narrowest scope necessary for the code to function is better than a file-global import. Your thoughts?

**Comment by braedon** [comment]
I can shift the import into the objects?

**Comment by echojc** [comment]
Sounds good.

**Comment by braedon** [comment]
Imports changed

**Comment by echojc** [comment]
Should the import in GpmService be inside SearchResult?

**Comment by braedon** [comment]
Doone

**Comment by echojc** [comment]
Wait are the ones inside the classes necessary? The only JsonFormats required in the class should be available from the companion objects...?

Sorry only have my phone so it's hard for me to tell.

**Comment by braedon** [comment]
Inside the GpmService class? I think something in JsonProtocol is needed for the spray marshaling/unmarshaling. Can't remember exactly, but it error'd without that import.

**Pull request merged**
